### ISSUE TITLE
Request schema not validating unknown fields in request json

### ISSUE THREAD

**Issue by wanderer056** [maximdanilchenko/aiohttp-apispec#132] opened 2023-11-06 05:06 UTC
It validates for invalid type like when str is passed to the int field but does not validate for unknown fields in the json schema. Looking at the documentation of marshmallow and webargs it says it raises an error by default for unknown fields.
Eg:

```
class RequestSchema(Schema):
    id = fields.Int()
    name = fields.Str()


@docs(
    tags=["mytag"],
    summary="Test method summary",
    description="Test method description",
)
@request_schema(RequestSchema)
async def index(request):
    print(request["data"])
    return web.json_response({"msg": "done", "data": {}})


app = web.Application()
app.router.add_post("/v1/test", index)
app.middlewares.append(validation_middleware)

setup_aiohttp_apispec(
    app=app,
    title="My Documentation",
    version="v1",
    url="/api/docs/swagger.json",
    swagger_path="/api/docs",
)
```

Request : ``` curl -X POST http://localhost:8000/v1/test -H 'Content-Type: application/json' -d '{"id":"abc"}' ```
Response:```{"id": ["Not a valid integer."]}```

BUTTT

Request: ```curl -X POST http://localhost:8000/v1/test -H 'Content-Type: application/json' -d '{"unknownfield":"test"}' ```
Response: ```{"msg": "done", "data": {}}```

**Comment by wanderer056** [comment] 2023-11-07 04:41
Looking more at the issue. I tried using the webargs framework itself for validation. Same problem exists in webargs=5.5.3 but there is no issue in webargs=8.3.0.

**Comment by kiforchuk** [comment] 2024-11-09 16:35
@wanderer056 That's the same issue as https://github.com/maximdanilchenko/aiohttp-apispec/issues/96
It was already resolved by https://github.com/maximdanilchenko/aiohttp-apispec/pull/112 which contains webargs upgrade

Those changes are in beta now, you can apply them by updating `aiohttp-apispec` to 3.0.0b1:
`pip install aiohttp-apispec==3.0.0b1`

Detailed explanation of the root cause can be found [here](https://github.com/maximdanilchenko/aiohttp-apispec/issues/96#issuecomment-727983192)

**Closed by kiforchuk** 2024-11-09 16:35 UTC
